//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opennest_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("opennest_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bbox_edges {
            get {
                object obj = ResourceManager.GetObject("bbox_edges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;bbfont name=&quot;VDA&quot; style=&quot;bold&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;!-- SPACE --&gt;
        ///  &lt;letter code=&quot;32&quot; start=&quot;0.2&quot; end=&quot;0.5&quot; /&gt;
        ///  &lt;!-- NULL --&gt;
        ///  &lt;letter code=&quot;0&quot; start=&quot;0&quot; end=&quot;0.7&quot;&gt;
        ///    &lt;path x=&quot;0.10&quot; y=&quot;0.90&quot;&gt;
        ///      &lt;to x=&quot;0.60&quot; y=&quot;0.90&quot; /&gt;
        ///      &lt;to x=&quot;0.60&quot; y=&quot;0.10&quot; /&gt;
        ///      &lt;to x=&quot;0.10&quot; y=&quot;0.10&quot; /&gt;
        ///      &lt;to x=&quot;0.10&quot; y=&quot;0.90&quot; /&gt;
        ///    &lt;/path&gt;
        ///    &lt;path x=&quot;0.05&quot; y=&quot;1.00&quot;&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;1.00&quot; /&gt;
        ///      &lt;to x=&quot;0.70&quot; y=&quot;0.95&quot; b=&quot;0.414213562373095&quot; /&gt;
        ///      &lt;to x=&quot;0. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bold {
            get {
                return ResourceManager.GetString("bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap element {
            get {
                object obj = ResourceManager.GetObject("element", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap element_surface {
            get {
                object obj = ResourceManager.GetObject("element_surface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap element_rhino {
            get {
                object obj = ResourceManager.GetObject("element_rhino", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap element_rhino_layer {
            get {
                object obj = ResourceManager.GetObject("element_rhino_layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hull {
            get {
                object obj = ResourceManager.GetObject("hull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap inscribe_circle {
            get {
                object obj = ResourceManager.GetObject("inscribe_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap large_icon {
            get {
                object obj = ResourceManager.GetObject("large_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nest_collision {
            get {
                object obj = ResourceManager.GetObject("nest_collision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap simplify {
            get {
                object obj = ResourceManager.GetObject("simplify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nest_options {
            get {
                object obj = ResourceManager.GetObject("nest_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nest_rhino_geo {
            get {
                object obj = ResourceManager.GetObject("nest_rhino_geo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap opennest {
            get {
                object obj = ResourceManager.GetObject("opennest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap opennest_2 {
            get {
                object obj = ResourceManager.GetObject("opennest_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pack_objects {
            get {
                object obj = ResourceManager.GetObject("pack_objects", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap packing_boxes {
            get {
                object obj = ResourceManager.GetObject("packing_boxes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pca {
            get {
                object obj = ResourceManager.GetObject("pca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap project {
            get {
                object obj = ResourceManager.GetObject("project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap region_slits {
            get {
                object obj = ResourceManager.GetObject("region_slits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;bbfont name=&quot;VDA&quot; style=&quot;regular&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;!-- SPACE --&gt;
        ///  &lt;letter code=&quot;32&quot; start=&quot;0.20&quot; end=&quot;0.50&quot; /&gt;
        ///  &lt;!-- NULL --&gt;
        ///  &lt;letter code=&quot;0&quot; start=&quot;0&quot; end=&quot;0.7&quot;&gt;
        ///    &lt;path x=&quot;0.05&quot; y=&quot;0.95&quot;&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;0.95&quot; /&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;0.05&quot; /&gt;
        ///      &lt;to x=&quot;0.05&quot; y=&quot;0.05&quot; /&gt;
        ///      &lt;to x=&quot;0.05&quot; y=&quot;0.95&quot; /&gt;
        ///    &lt;/path&gt;
        ///  &lt;/letter&gt;
        ///  &lt;!-- LATIN CAPITAL LETTER A --&gt;
        ///  &lt;letter code=&quot;65&quot; start=&quot;0.00&quot; end=&quot;0.70&quot;&gt;
        ///    &lt;path x=&quot;0.133333333333333&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string regular {
            get {
                return ResourceManager.GetString("regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;bbfont name=&quot;VDA&quot; style=&quot;regular&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;!-- SPACE --&gt;
        ///  &lt;letter code=&quot;32&quot; start=&quot;0.20&quot; end=&quot;0.50&quot; /&gt;
        ///  &lt;!-- NULL --&gt;
        ///  &lt;letter code=&quot;0&quot; start=&quot;0&quot; end=&quot;0.7&quot;&gt;
        ///    &lt;path x=&quot;0.05&quot; y=&quot;0.95&quot;&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;0.95&quot; /&gt;
        ///      &lt;to x=&quot;0.65&quot; y=&quot;0.05&quot; /&gt;
        ///      &lt;to x=&quot;0.05&quot; y=&quot;0.05&quot; /&gt;
        ///      &lt;to x=&quot;0.05&quot; y=&quot;0.95&quot; /&gt;
        ///    &lt;/path&gt;
        ///  &lt;/letter&gt;
        ///  &lt;!-- LATIN CAPITAL LETTER A --&gt;
        ///  &lt;letter code=&quot;65&quot; start=&quot;0.00&quot; end=&quot;0.70&quot;&gt;
        ///    &lt;path x=&quot;0.133333333333333&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string regularCurves {
            get {
                return ResourceManager.GetString("regularCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sheet {
            get {
                object obj = ResourceManager.GetObject("sheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sheet_surface {
            get {
                object obj = ResourceManager.GetObject("sheet_surface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap text {
            get {
                object obj = ResourceManager.GetObject("text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap transform_element_rhino {
            get {
                object obj = ResourceManager.GetObject("transform_element_rhino", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unroll {
            get {
                object obj = ResourceManager.GetObject("unroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap merge {
            get {
                object obj = ResourceManager.GetObject("merge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
