import math, xml.etree.ElementTree as ET, sys, os

ARC_STEP = math.radians(15.0); _ARC_MIN = 2

def arc_points(p1, tangent, p2):
    x1,y1=p1; x2,y2=p2; tx,ty=tangent
    tl=math.hypot(tx,ty)
    if tl<1e-12: return [(x2,y2)]
    tx,ty=tx/tl,ty/tl; nx,ny=-ty,tx
    dx,dy=x1-x2,y1-y2; denom=2.0*(dx*nx+dy*ny)
    if abs(denom)<1e-12: return [(x2,y2)]
    s=-(dx*dx+dy*dy)/denom; cx,cy=x1+s*nx,y1+s*ny
    r=math.hypot(x1-cx,y1-cy); a1=math.atan2(y1-cy,x1-cx); a2=math.atan2(y2-cy,x2-cx)
    if (-math.sin(a1))*tx+(math.cos(a1))*ty>=0: sweep=(a2-a1)%(2*math.pi)
    else: sweep=-((a1-a2)%(2*math.pi))
    segs=max(_ARC_MIN,int(math.ceil(abs(sweep)/ARC_STEP)))
    return [(cx+r*math.cos(a1+sweep*i/segs), cy+r*math.sin(a1+sweep*i/segs)) for i in range(1,segs+1)]

def parse_glyph(letter):
    start=float(letter.get("start",0.0)); end=float(letter.get("end",0.7)); strokes=[]
    for path in letter.findall("path"):
        lx,ly=float(path.get("x")),float(path.get("y")); pts=[(lx,ly)]
        for to in path.findall("to"):
            tox,toy=float(to.get("x")),float(to.get("y")); b=to.get("b")
            if b is None: pts.append((tox,toy))
            else:
                d2=2.0*math.atan(float(b)); cs,sn=math.cos(d2),math.sin(d2)
                chx,chy=tox-lx,toy-ly; tangent=(chx*cs-chy*sn,chx*sn+chy*cs)
                pts.extend(arc_points((lx,ly),tangent,(tox,toy)))
            lx,ly=tox,toy
        strokes.append(pts)
    return code_of(letter),start,end,strokes

def code_of(letter): return int(letter.get("code"))

def load(path):
    root=ET.fromstring(open(path,encoding="utf-8").read())
    glyphs=[parse_glyph(l) for l in root.findall("letter")]
    return glyphs

def emit(name, glyphs, out):
    pts=[]; stroke_off=[]; stroke_n=[]
    g_code=[]; g_start=[]; g_end=[]; g_s0=[]; g_ns=[]
    for code,start,end,strokes in glyphs:
        g_code.append(code); g_start.append(start); g_end.append(end)
        g_s0.append(len(stroke_off)); g_ns.append(len(strokes))
        for s in strokes:
            stroke_off.append(len(pts)//2); stroke_n.append(len(s))
            for (x,y) in s: pts.append(x); pts.append(y)
    def arr(t,n,vals,fmt): 
        out.write(f"static const {t} {name}_{n}[] = {{")
        out.write(",".join(fmt(v) for v in vals) if vals else "0")
        out.write("};\n")
    arr("float","pts",pts,lambda v:f"{v:.6g}")
    arr("int","stroke_off",stroke_off,str)
    arr("int","stroke_n",stroke_n,str)
    arr("int","g_code",g_code,str)
    arr("float","g_start",g_start,lambda v:f"{v:.6g}")
    arr("float","g_end",g_end,lambda v:f"{v:.6g}")
    arr("int","g_s0",g_s0,str)
    arr("int","g_ns",g_ns,str)
    out.write(f"static const EngFont {name}_font = {{ {name}_pts, {name}_stroke_off, {name}_stroke_n, "
              f"{name}_g_code, {name}_g_start, {name}_g_end, {name}_g_s0, {name}_g_ns, {len(g_code)} }};\n\n")

FONTDIR=sys.argv[1]; OUT=sys.argv[2]
with open(OUT,"w",encoding="utf-8") as out:
    out.write("// Generated by tools/bake_engraving_font.py from the OpenNest VDA single-stroke fonts.\n")
    out.write("// Glyph strokes are pre-sampled (arcs -> segments at ~15 deg). DO NOT EDIT BY HAND.\n")
    out.write("struct EngFont { const float* pts; const int* stroke_off; const int* stroke_n;\n")
    out.write("    const int* g_code; const float* g_start; const float* g_end; const int* g_s0; const int* g_ns; int n_glyphs; };\n\n")
    emit("eng_regular", load(os.path.join(FONTDIR,"regular.xml")), out)
    emit("eng_bold",    load(os.path.join(FONTDIR,"bold.xml")), out)
print("baked", OUT)
